### ISSUE TITLE
urbit.org docs: relative links go to the wrong subdomain

### ISSUE THREAD

**Issue by bacwyls** [urbit/developers.urbit.org#27]
See this web page:
https://developers.urbit.org/reference/glossary/moon

the bottom two links in the page go to  ```developers.urbit.org/relative_link``` instead of ```urbit.org/relative_link```
so clicking the link results in a 404.

**Comment by hosted-fornet** [comment]
Related but different: the "Edit this page on GitHub" links point to the wrong place. For example, in the Hoon School guides [like this page on Types](https://developers.urbit.org/guides/core/hoon-school/E-types), it points to 

https://github.com/urbit/developers.urbit.org/blob/main/content/docs/core/hoon-school/E-types.md

rather than

https://github.com/urbit/developers.urbit.org/blob/main/content/guides/core/hoon-school/E-types.md

**Comment by sigilante** [comment]
#31

**Comment by sigilante** [comment]
Related @matildepark:

/reference/arvo has an Edit on Github link, but can't be edited because it's actually /reference/arvo/_index.md.

**Comment by matildepark** [comment]
> Related @matildepark:
> 
> /reference/arvo has an Edit on Github link, but can't be edited because it's actually /reference/arvo/_index.md.

We have a catch for that (https://github.com/urbit/developers.urbit.org/blob/a52608c85871e9d3061d848816f1cac7d98bae74/pages/reference/%5B%5B...slug%5D%5D.js#L83) but will have to see what params.slug is here.

**Comment by matildepark** [comment]
I think between @sigilante and @nogira all these have been covered.
